san650/ember-cli-page-object

DOCUMENTATION.md
test-support/page-object.js
test-support/page-object/actions.js
test-support/page-object/attribute.js
test-support/page-object/collection.js
test-support/page-object/predicates.js
test-support/page-object/queries.js
tests/unit/actions/clickable-test.js
tests/unit/actions/fillable-test.js
tests/unit/actions/visitable-test.js
tests/unit/predicates/has-class-test.js
tests/unit/predicates/is-hidden-test.js
tests/unit/predicates/is-visible-test.js
tests/unit/predicates/not-has-class-test.js
tests/unit/queries/attribute-test.js
tests/unit/queries/count-test.js
tests/unit/queries/text-test.js
tests/unit/queries/value-test.js
tests/unit/test-helper.js

The idea is that every attribute (i.e. `.hasClass`, `.isVisible`, `.clickable`, etc.) is an `Attribute` object.
Each attribute type executes a specific method within a context. That context has the `page`, `key`, `selector` and other attribute's options.
This makes it easy to create cross attribute functionality such as calculating the full qualified selector and it simplifies the creation of new functionalities (that will be shared on all attributes) such as index (see #3) and more to come.
This refactor is backwards compatible :smile_cat:

Restructure attributes

---

DOCUMENTATION.md
test-support/page-object/build.js
test-support/page-object/collection.js
test-support/page-object/helpers.js
tests/unit/components/collection-test.js
tests/unit/components/component-test.js
tests/unit/test-helper.js

Fix scopes

---

tests/unit/components/component-test.js

Define attributes without a selector if the page has an scope defined

---

test-support/page-object/actions.js
tests/unit/actions/visitable-test.js

This allows you to do the following:
```javascript
let userPage = PO.build({
visit: PO.visitable('/users/:id')
});
userPage.visit({id: 5});
```

Add support for dynamic segments in visitable urls

---

test-support/page-object/actions.js
test-support/page-object/build.js
tests/acceptance/login-test.js

The way actions are chainable is awesome, but one downside is that you can't use ES7's `async`/`await` with page objects, since actions return `this` instead of a promise.
This change makes it so that `Component` can act like a promise by implementing a `then` method. This allows you to do the following:
```javascript
test('login', async function(assert) {
assert.expect(2);
await page
.visit()
.form()
.userName('user@example.com')
.password('secret')
.click();
assert.ok(page.notHasError(), 'Page doesn\'t have error');
assert.equal(page.message(), 'Valid user!');
});
```
I wasn't sure of the best way to test this. I could write an acceptance test using async/await, but I am not sure what side-effects turning on Babel's `es7.asyncFunctions` feature would have for apps using this add-on.
Do …

Allow Components to act like a promise so async/await works

---

test-support/page-object/helpers.js
tests/unit/queries/text-test.js

This change will allow to write page objects without knowledge of how text is broken down on multiple lines, making tests less fragile.

Normalize whitespaces in the way browser does it

---

README.md

emberobserver.com likes build badges to be on top of the readme file

Move travis-ci build badge to top

---

test-support/page-object/actions.js

Query params are optional and would just be tacked onto the end of the existing url, if they are specified.

Provide queryParam support for visitable action

---

test-support/page-object/helpers.js
tests/unit/queries/text-test.js

This modifies the regular expressions a bit to make sure that `&nbsp;` whitespace characters are converted to standard whitespace characters.

Support Normalizing &nbsp; characters in Text trim

---

test-support/page-object/actions.js

`Ember.keys` is deprecated, this avoids using it unless `Object.keys` in unsupported (which is only IE8 which is unsupported by Ember anyway http://kangax.github.io/compat-table/es5/#Object.keys)

Silence deprecation warning for Ember.keys

---

tests/unit/components/collection-test.js

Hey, here is a test showing that nested collections aren’t inheriting the scope of their containing collection. I see that you [recently fixed something related to collection scope](https://github.com/san650/ember-cli-page-object/releases/tag/v0.8.1) and the changes look pretty in-depth, so I suspect you’d be much quicker at fixing this than me.
Or maybe I’m just mistaken and this is expected behaviour?

Nested collections are not properly scoped

---

blueprints/page-object-component/files/tests/pages/components/__name__.js

Fixes generated deprecation error discussed in https://github.com/san650/ember-cli-page-object/issues/77
This doesn't update the documentation, though.

Removes PageObject.component from the page-object-component blueprint.

---

blueprints/page-object/files/tests/pages/__name__.js
blueprints/page-object/index.js

Currently making a page nested in a namespace leads to failing module look up because the blueprint uses `../page-object`.
So the command `ember g page-object parent/child` will fail silently if you try use this new page object generated.
This instead uses the same pattern as the Acceptance test generator from Ember CLI to use the fully qualified module name for the `page-object` module.

Allow nested pages with full path to "page-object" module

---

package.json

Generators use `ember-cli-string-utils` to generate the app name but we forgot to declare the dependency in the package.json file.

Missing `ember-cli-string-utils` dependency

---

test-support/page-object/helpers.js
test-support/page-object/properties/attribute.js
test-support/page-object/properties/contains.js
test-support/page-object/properties/count.js
test-support/page-object/properties/has-class.js
test-support/page-object/properties/is-hidden.js
test-support/page-object/properties/is-visible.js
test-support/page-object/properties/not-has-class.js
test-support/page-object/properties/value.js
tests/unit/actions/click-on-text-test.js
tests/unit/actions/clickable-test.js
tests/unit/actions/fillable-test.js
tests/unit/actions/visitable-test.js
tests/unit/components/collection-test.js
tests/unit/create-test.js
tests/unit/predicates/contains-test.js
tests/unit/predicates/has-class-test.js
tests/unit/predicates/is-hidden-test.js
tests/unit/predicates/is-visible-test.js
tests/unit/predicates/not-has-class-test.js
tests/unit/queries/attribute-test.js
tests/unit/queries/count-test.js
tests/unit/queries/text-test.js
tests/unit/queries/value-test.js
tests/unit/shared.js

Assert predicates and queries only match one element

---

CHANGELOG.md
test-support/page-object/properties/click-on-text.js
tests/unit/actions/click-on-text-test.js

Now the property can match both, current element or child elements
Fixes #114

Change `.clickOnText` to match current element

---

CHANGELOG.md
test-support/page-object/properties/visitable.js
tests/unit/actions/visitable-test.js

Instead of receiving two distinct object parameters (dynamic segments
and query params) now it receives only one.
The idea is to fill the dynamic segments first using the values from
the param that match the keys and then use the rest of the keys and
values as query params.
e.g.
```
var page = create({
visit: visitable('/users/:user_id')
})
page.visit({ user_id: 1, expanded: true });
// is equivalent to
visit("/users/1?expanded=true")
```
Fixes #113

Change `.visitable` signature

---

docs.js

Changes docs destination path in docs.js from `api/methods` to one automatically generated based on the version number in package.json.
Removes permalink from markdown frontmatter.
Improves `console.log` messages in docs.js.

Autogenerate API docs path from version number

---

docs.js
test-support/page-object/actions/click-on-text.js
test-support/page-object/actions/clickable.js
test-support/page-object/actions/fillable.js
test-support/page-object/actions/visitable.js
test-support/page-object/collection.js
test-support/page-object/create.js
test-support/page-object/helpers.js
test-support/page-object/predicates/contains.js
test-support/page-object/predicates/has-class.js
test-support/page-object/predicates/is-hidden.js
test-support/page-object/predicates/is-visible.js
test-support/page-object/predicates/not-has-class.js
test-support/page-object/queries/attribute.js
test-support/page-object/queries/count.js
test-support/page-object/queries/text.js
test-support/page-object/queries/value.js

Includes replacing `var` and `let` with `const` (just in the docs), per the convention in the Ember Guides.

Copy edit JSDoc inline documentation

---

package.json
test-support/page-object/actions/clickable.js
test-support/page-object/actions/fillable.js
test-support/page-object/predicates/contains.js
test-support/page-object/predicates/has-class.js
test-support/page-object/predicates/is-hidden.js
test-support/page-object/predicates/is-visible.js
test-support/page-object/predicates/not-has-class.js
test-support/page-object/queries/attribute.js
test-support/page-object/queries/count.js
test-support/page-object/queries/text.js
test-support/page-object/queries/value.js

While merging #99, most of the new inline JSDoc disappeared. This PR re-adds it.

Re-add JSDoc documentation that vanished during merge

---

README.md

This is just an update to the link to Selenium Page Object information. The current link is outdated and redirects to https://github.com/seleniumhq/selenium-google-code-issue-archive

Update link to selenium page objects information

---

addon/collection.js
tests/helpers/with-iterator-symbol-defined.js
tests/unit/components/collection-test.js

This PR implements the changes discussed in https://github.com/san650/ember-cli-page-object/issues/54. @san650 it also includes the delegation of array methods we talked about, since it was easy to add them while I was in there. If you'd prefer to have that addressed in a separate PR, I'm happy to pull them out.
With this change, the following properties are now added to collection objects on creation if they haven't already been defined:
- a `toArray()` method that returns an array containing the elements of the collection
- a `[Symbol.iterator]()` method which yields each item in the collection sequentially (only if `Symbol.iterator` is present in the current environment)
- `map`, `mapBy`, `filter`, and `filterBy` methods, all of which just delegate to the methods of the same name on …

Make collections easier to enumerate

---

addon/index.js
addon/queries/is.js
test-support/page-object.js
tests/unit/queries/is-test.js

Closes #147.
Adds the query `PageObject.is()`, which validates if an element (or elements) matches a given selector.
Useful for checking if an element (or elements) matches a selector like `:disabled` or `:checked`, which can be the result of either an attribute (`disabled="disabled"`, `disabled=true`) or a property (`disabled`).
(Uses jQuery's [`.is()`](http://api.jquery.com/is/).)
Examples:
```js
// <input type="checkbox" checked="checked">
// <input type="checkbox" checked>
const page = PageObject.create({
areInputsChecked: is(':checked', 'input', { multiple: true })
});
assert.equal(page.areInputsChecked, true, 'Inputs are checked');
``` 
```js
// <button class="toggle-button active" disabled>Toggle something</button>
const page = PageObject.create({
isToggleButtonActive: …
```

Add .is property

---

addon/actions/triggerable.js
test-support/page-object.js
tests/unit/actions/triggerable-test.js

This pull request adds the focus property and it also includes it by default on every component.
```js
const page = PageObject.create({
scope: '#page',
focusOnName: triggerable('focus', 'input')
};
page.focusOnName(); // focuses on "#page input"
```

Add triggerEvent property

---

addon/actions/click-on-text.js
addon/actions/clickable.js
addon/helpers.js
tests/unit/actions/click-on-text-test.js
tests/unit/actions/clickable-test.js

And to maintain backwards compatibility we set this option to false.
Fixes #6

Make visibility validation optional for clickable and click-on-text

---

.jscsrc
package.json
tests/acceptance/actions-test.js
tests/acceptance/default-properties-test.js
tests/dummy/app/components/calculating-device.js
tests/dummy/app/controllers/calculator.js
tests/helpers/module-for-acceptance.js
tests/integration/actions-test.js
tests/integration/context-test.js
tests/integration/default-properties-test.js
tests/unit/actions/click-on-text-test.js
tests/unit/actions/clickable-test.js
tests/unit/actions/fillable-test.js
tests/unit/actions/triggerable-test.js
tests/unit/actions/visitable-test.js
tests/unit/components/collection-test.js
tests/unit/create-test.js
tests/unit/queries/attribute-test.js
tests/unit/queries/count-test.js
tests/unit/queries/is-test.js
tests/unit/queries/property-test.js
tests/unit/queries/text-test.js
tests/unit/queries/value-test.js
tests/unit/test-helper.js

Fixes #180 
Fix some indentation issues
Change var to let
Remove multiple variable declarations
Add a space after the switch keyword
Disable requireSpread rule in tests/helpers/module-for-acceptance.js file
Change const to let when used inside functions, const should be used only at module level
Add parenthesis to the arrow functions
Remove multiple line breaks
Disable requireCamelCaseOrUpperCase rule in test_throws_if_not_multiple. It should be camel case but it used all over the project.

Add ember-suave

---

addon/index.js
test-support/page-object.js

After upgrading to `1.3.0` from `1.1.0` I noticed that getContext wasn't available from `import { getContext } from 'ember-cli-page-object'` 
This PR fixes that :)

Expose getContext

---

test-support/page-object.js
tests/unit/addon-exports-test.js

This PR adds tests to validate that we're exporting via:
* `import { foo } from 'ember-cli-page-object';`
* `import PageObject from 'ember-cli-page-object'; PageObject.foo`
* `import { foo } from 'my-app/tests/page-object'`;
* `import PageObject from 'my-app/tests/page-object'; PageObject.foo`

Test exports

---

addon/actions/triggerable.js
tests/unit/actions/triggerable-test.js

Add `eventProperties` options to maintain compatibility with Ember's `triggerEvent` test helper.
After this pull request this will work:
```js
const page = PageObject.create({
enter: triggerable('keypress', '.name', { eventProperties: { keyCode: 13 } })
});
```

Pass event properties to triggerEvent helper

---

addon/-private/create.js
addon/-private/properties/fillable.js
tests/acceptance/actions-test.js
tests/dummy/app/router.js
tests/dummy/app/templates/inputs.hbs
tests/properties/fillable-test.js
tests/unit/create-test.js

This PR enhances the `fillable` property to support an additional `clue` parameter when filling a value. This value is used to filter the target input value.
It also adds `fillIn` and `select` as default properties to every page object component.
e.g.
```html
<input id="foo">
<input name="bar">
<input placeholder="baz">
```
```
const page = create({});
page
.fillIn('foo', 'value for input foo')
.fillIn('bar', 'value for input bar')
.fillIn('baz', 'value for input baz');
```
Note that the first parameter is optional and if used, it will filter the target input.
Apart from working with `input`s, this works with `textarea`s and `select`s HTML elements, and the rules that are used to filter the elements are
```
.scope input[data-test="${clue}"],
.scope input[aria-label="${clue}"],
.scope …
```

Fill in by label

---

addon/-private/create.js
tests/unit/create-test.js

Allows to configure a path for the page object which auto-generates a
visitable helper. This commit augments the `create` helper to add an
optional first parameter.
```js
const page = create('/foo');
page.visit(); // navigates to /foo
```
You can pass a second parameter with the PO definition
```js
const page = create('/foo', { /* PO definition */ });
```

Add path param to `create` helper

---

docs/v0.11.x/index.md
docs/v1.5.x/index.md
docs/v1.6.x/index.md

This fixes this issue I posted here: https://github.com/san650/ember-cli-page-object/issues/261

Fix link to Selenium's wiki page in docs

---

.travis.yml
config/ember-try.js

This should run `npm run nodetest` on Travis as a separate parallel job.

add node-tests to CI

---

addon/-private/dsl.js
tests/properties/dsl-test.js

Implements https://github.com/san650/ember-cli-page-object/issues/227.
It works on any page object node, not just collections.
Fixes #227.

Add `as` property to DSL.

---

.travis.yml

Right now `node-test` is the last build to start in Travis and it's also the slowest, by making it the first one to start we can reduce the overall time the CI takes to finish.

Make node-test run first in Travis

---

docs/v1.6.x/components.md
docs/v1.7.x/components.md
docs/v1.8.x/components.md

This is true according to the 1.6.0 release notes:
https://github.com/san650/ember-cli-page-object/releases/tag/v1.6.0
Note that these don’t exactly align to the links in each file as I believe they are incorrect… another PR forthcoming.

Add value as default component attribute

---

docs/v1.7.x/api/create.md
docs/v1.7.x/components.md
docs/v1.8.x/api/create.md
docs/v1.8.x/components.md

Hey, it seemed to me that these links should be within the version you’re currently looking at, rather than always to 1.6.x, do you agree?

Correct property links to be in current version

---

addon/-private/extend/find-element-with-assert.js
addon/-private/extend/find-element.js
addon/-private/helpers.js
addon/-private/properties/attribute.js
addon/-private/properties/click-on-text.js
addon/-private/properties/clickable.js
addon/-private/properties/collection.js
addon/-private/properties/contains.js
addon/-private/properties/count.js
addon/-private/properties/fillable.js
addon/-private/properties/has-class.js
addon/-private/properties/is-hidden.js
addon/-private/properties/is-visible.js
addon/-private/properties/is.js
addon/-private/properties/not-has-class.js
addon/-private/properties/text.js
addon/-private/properties/triggerable.js
addon/-private/properties/value.js

The linter can be run like `find addon -type f -name '*.js' -exec node node_modules/documentation/bin/documentation.js --lint --shallow {} \;`

Fix jsdoc lining errors

---

config/ember-try.js
node-tests/blueprints/component-test-test.js
node-tests/blueprints/page-object-component-test.js
tests/helpers/properties/integration-adapter.js
tests/integration/actions-test.js
tests/test-helper.js

ember@2.11.3 introduces a (breaking?) change in how exceptions are
propagated in backburner which causes some test that were previously
working, to fail.
See https://github.com/emberjs/ember.js/pull/14898#issuecomment-285510703
Also fix some descriptions in blueprint tests

Do not use assert.throws when testing actions in integration tests

---

addon/-private/better-errors.js
addon/-private/execution_context/acceptance.js
addon/-private/execution_context/helpers.js
addon/-private/execution_context/integration.js
addon/-private/properties/alias.js
tests/properties/alias-test.js

- Improve error-reporting of `alias` helper by using `throwBetterError`
- `throwBetterError`: make `selector` part of an optional `options` parameter so that it can be excluded when there is no selector to include in the error message. 
- `alias`: use `throwBetterError` to build the `Ember.Error` thrown when an aliased property is not found on the page object.

Use throwBetterError in alias helper

---

addon/-private/better-errors.js
tests/unit/-private/better-errors-test.js
tests/unit/-private/helpers-test.js
tests/unit/-private/properties/alias-test.js
tests/unit/-private/properties/attribute-test.js
tests/unit/-private/properties/click-on-text-test.js
tests/unit/-private/properties/clickable-test.js
tests/unit/-private/properties/collection-test.js
tests/unit/-private/properties/contains-test.js
tests/unit/-private/properties/count-test.js
tests/unit/-private/properties/create-test.js
tests/unit/-private/properties/dsl-test.js
tests/unit/-private/properties/fillable-test.js
tests/unit/-private/properties/has-class-test.js
tests/unit/-private/properties/is-hidden-test.js
tests/unit/-private/properties/is-test.js
tests/unit/-private/properties/is-visible-test.js
tests/unit/-private/properties/not-has-class-test.js
tests/unit/-private/properties/property-test.js
tests/unit/-private/properties/text-test.js
tests/unit/-private/properties/triggerable-test.js
tests/unit/-private/properties/value-test.js
tests/unit/-private/properties/visitable-test.js

- Ensure that `throwBetterError` logs an error to the console.
- Addresses #304 
- Call `Ember.Logger.error` before throwing `Ember.Error`.
- Added unit tests for `throwBetterError`, which I probably should have done in #303, since `throwBetterError` now has some logic around whether or not to report a selector.
- I wasn't sure at first where to put the test for `throwBetterErrors`, so I reshuffled the `tests` folders a bit.

throwBetterError logs error to console

---

addon/-private/properties/triggerable.js
tests/unit/-private/properties/triggerable-test.js

Some events can be triggered without any specified properties (e.g., `mousedown`), but others require properties like `which` (e.g., `keydown`). `triggerable` currently requires event properties to be defined at the time when `triggerable` is called in the page object, but it is sometimes more convenient to specify event properties at the time when the triggerable descriptor is used in tests. This PR modifies `triggerable` to accept either static event properties defined at the time when `triggerable` is called in the page object or dynamic event properties passed in when the descriptor is accessed.
- New tests verify that `triggerable` descriptor applies the event properties.
- New tests verify that if event properties are specified both in the `triggerable` call and the `triggerable` …

Triggerable returns function with eventProperties parameter

---

tests/helpers/properties/acceptance-adapter.js
tests/helpers/properties/integration-adapter.js
tests/unit/-private/properties/alias-test.js
tests/unit/-private/properties/click-on-text-test.js
tests/unit/-private/properties/clickable-test.js
tests/unit/-private/properties/dsl-test.js
tests/unit/-private/properties/fillable-test.js
tests/unit/-private/properties/triggerable-test.js

Current approach for testing properties doesn't scale very well. For example it's impossible to run existing properties tests against alternative contexts like [native contexts](https://github.com/san650/ember-cli-page-object/pull/325).
The general idea of this pr is changing assertions like
```js
this.adapter.click((actualSelector) => assert.equal(actualSelector, expectedSelector));
```
to
```js
this.adapter.$(expectedSelector).on('click', () => assert.ok(true));
```
This way we don't test internals of contexts anymore.
@san650 There is some work left to do here(mostly cleanup). Anyway I would appreciate your thoughts on this change. Does this approach make sense to you?

change property unit tests to assert against real DOM

---

tests/unit/-private/properties/property-test.js

The reason for this change is that absence of type="checkbox" attribute prevents ` .checked` property to be properly calculated in IE
I know we don't have IE on CI but locally it fails.

Fix checkbox declarations in tests

---

index.js

Only addons that are immediately included at the root level app actually get access to the app, but addons can also traverse their ancestry to find that root level addon. This adds a function based on the private [`findHost` function in ember-cli itself](https://github.com/ember-cli/ember-cli/blob/master/lib/models/addon.js#L613). While the method is private, other addons such as ember-test-selectors, ember-bootstrap, and [plenty of others](https://emberobserver.com/code-search?codeQuery=findHost) do use it, and since it's based on the tree structure that addons have it's pretty unlikely that it will break on us soon.
I can confirm that this fixes #337 locally, happy to try to add a test in node-tests as well if needed

bugfix(nested-usage): Fixes nested addon usage by finding the host

---

index.js
vendor/shims/ecpo-jquery-global.js
vendor/shims/ecpo-jquery.js
vendor/shims/project-jquery.js

This should fix issues like the one described by @magistrula in slack:
> I ran my tests without calling `useNativeEvents`, and here’s what I’m observing: if I run my tests on `v.1.12.0`, some tests pass that expect an empty `div` not to be visible. If I run my tests on `v1.13.0-alpha.1`, those tests fail. However, this test fails in ember-cli-page-object if I checkout to `v1.12.0` and when I checkout to `v1.13.0-alpha.1`
Also it simplifies inclusion of `jquery`. Thanks to @pzuraq for the idea.

Use project's jquery if available

---

index.js

Our fastboot builds were failing for local development.  This prevents the addon from enabling itself in the fastboot build. (Addon depends on jquery)

Fastboot Safe

---

addon/-private/properties/collection.js
addon/-private/properties/collection/legacy.js
addon/-private/properties/collection/main.js
tests/unit/-private/properties/collection-test.js
tests/unit/-private/properties/legacy-collection-test.js

This PR implements the new Collection API RFC outlined in #352. The new API is optionally applied if users omit `itemScope` from collection definitions, allowing them to opt into the new syntax over time.
The new collection is implemented as a class, that has a single instance per collection, rather than returning a new one each time the collection is called. Users are meant to interact with this class directly rather than calling the collection like method as before.
The class also caches individual item pages internally so they don't have to be regenerated each time the collection is accessed. This allows us to optimize for CPU over memory usage, which will (incrementally) help test speed.
The new API that is exposed has the following methods:
* `objectAt`: Returns the item at the …

feat(collection): Exposes a new Collection API 

---

docs.js

We updated the `documentation` module to `v5.3.3`, and now we need to update the command that builds the docs. 
**Sanity Check**:
After making these updates, I was able to successfully generate the docs that we will publish for `v1.13.0`.

Update documentation command

---

addon/-private/context.js
package.json
tests/integration/deprecations/page-render-test.js

part of [1.x deprecations](https://github.com/san650/ember-cli-page-object/issues/359)
TODO:
I haven't found any usages.

deprecate page.render()

---

addon/-private/compatibility.js
addon/-private/dsl.js
addon/-private/execution_context/acceptance-native-events.js
config/ember-try.js
package.json
tests/unit/-private/compatibility-test.js

- Remove `ember-test-helpers` from `dependencies` and rely on the host app to supply the test helpers, either via `ember-mocha` or `ember-qunit`. This will prevent `ember-cli-page-object` from clobbering the host app's version of the helpers. 
- Addresses https://github.com/san650/ember-cli-page-object/issues/361
- Remove `ember-test-helpers` from the list of `dependencies`
- Instead of importing `ember-test-helpers/wait`, create a new `wait` helper that throws an error if `ember-test-helpers` or `@ember-test-helpers` is not available.

Remove ember-test-helpers from dependencies

---

.travis.yml

We've just added [2 new](https://github.com/san650/ember-cli-page-object/pull/366/files#diff-d20f4baf61c4397c467d6218d0ba6a04R95) ember-try build configurations. I think this should be reflected in the travis config as well

include ember-test-helper specific configurations to travis

---

addon/-private/properties/collection.js
addon/-private/properties/collection/main.js
tests/integration/actions-test.js
tests/integration/deprecations/comma-separated-selector-test.js
tests/integration/deprecations/legacy-collection-test.js
tests/unit/-private/properties/collection-test.js

This PR changes the new collection's function signature:
before
```js
var page = create({
users: collection({
scope: 'table tr'
})
});
```
after
```js
var page = create({
users1: collection('table tr'),
users2: collection('table tr', {
text: text()
})
});
```
The main reason for this is that we don't have an easy way to distinguish uses of the legacy collection API from the new collection API.
This PR also renders a warning for missing `itemScope` property in legacy collection API.

Change collection signature

---

addon/-private/compatibility.js

When using `require()`, we're not guaranteed that the module we're `requiring` is resolved yet, so it could just be an empty object with no exports. This has actually happened to a user, although it's tightly tied to their module dependency graph, and I haven't been able to easily repro it, nor do I think writing a unit test for it is feasible :( But the fix is to "lazy call" the `@ember/test-helpers` methods so we can be assured that they are resolved by the time we call them, even if they aren't when we export our compatibility functions.

Fix compatibility exports

---

README.md

The current link is broken. There is an alternative link to official Selenium site https://www.seleniumhq.org/docs/06_test_design_considerations.jsp#page-object-design-pattern, but I like github wiki version more

Fix link to Page Objects article by Selenium

---

addon/-private/properties/attribute.js
addon/-private/properties/blurrable.js
addon/-private/properties/click-on-text.js
addon/-private/properties/clickable.js
addon/-private/properties/collection.js
addon/-private/properties/contains.js
addon/-private/properties/count.js
addon/-private/properties/fillable.js
addon/-private/properties/focusable.js
addon/-private/properties/getter.js
addon/-private/properties/has-class.js
addon/-private/properties/is-hidden.js
addon/-private/properties/is-present.js
addon/-private/properties/is-visible.js
addon/-private/properties/is.js
addon/-private/properties/not-has-class.js
addon/-private/properties/property.js
addon/-private/properties/text.js
addon/-private/properties/triggerable.js
addon/-private/properties/value.js
addon/-private/properties/visitable.js
guides/components.md
guides/extend.md
guides/index.md
guides/installation.md
guides/migrating.md
guides/native-events.md
guides/options.md
guides/quickstart.md

In this PR I've copied existing v1.13 docs from "gh-pages" to development branch and put it under the "guides/" directory.
The idea is to keep the freshest docs in the main branch and copy it to the gh-pages with a existing docs script as it currently happens for generated API docs. I believe locating of the guides alongside the code/API docs should improve a contributor experience. 
Also this PR contains refreshing of existing examples with a new syntax and some fixes. I hope commit messages are explanatory enough to follow what has happened.
todo:

Prepare docs 1.14

---

package.json

The current `ember-cli-babel` version `6.6.0` doesn't support the new modules syntax:

Upgrade `ember-cli-babel` version to use new modules syntax

---

addon-test-support/properties/contains.js

Example full text:
```js
// <span>super text</span>
// <span>regular text</span>
const page = PageObject.create({
spansContain: PageObject.contains('span', { multiple: true })
});
// all spans contain 'text'
assert.ok(page.spanContains('text'));
```
Link: http://ember-cli-page-object.js.org/docs/v1.4.x/api/predicates#contains

Correct example typo

---

README.md
addon-test-support/properties/collection.js

1. Documents 'resetScope' for the Collection API. The property still works in the new API when defined on the item definition but wasn't documented anywhere.
2. Remove `bower install` step in the README. There's no `bower.json` file anymore!

[DOC] Document 'resetScope' for the Collection API

---

.eslintrc.js
addon-test-support/-private/better-errors.js
tests/helpers/properties/acceptance-adapter.js
tests/helpers/properties/application-adapter.js
tests/helpers/properties/integration-adapter.js
tests/helpers/properties/rendering-adapter.js
tests/unit/-private/better-errors-test.js

It's deprecated in favor of the now-reliable console.* methods.

Remove Ember.Logger usage

---

index.js

Because of [this](https://github.com/ember-cli/ember-cli/commit/a3fef4e74091f05c95e92d5a72549047c4b38473#diff-392bb207fea8bcbeb4a084bb445f7cc7) change, we need to check for the presence of the `@ember/jquery` addon as well as `this.vendorFiles['jquery.js']` in order to determine if the project already has jQuery.

Fix jQuery detection for ember-cli@3.4

---

guides/quickstart.md

Another attemp to refresh the guides. This time I've focused on the "Quickstart" page only.
In order to explain things I've leveraged a calculator idea which I find a great example of PO usage.
I expect there may be some clumsy turns of speech in the proposed document. Hints to improve are highly appreciated!
My next immediate plan is to refresh a components page, which promises not to be such a huge rewrite like this is.
Part of https://github.com/san650/ember-cli-page-object/issues/412
Partially replaces https://github.com/san650/ember-cli-page-object/pull/415

[doc] Rewrite Quickstart page

---

addon-test-support/properties/collection/main.js

This is the last Ceibo's `value` usage mentioned in https://github.com/san650/ember-cli-page-object/pull/405

Use Ceibo descriptor `get` for new collection

---

addon-test-support/properties/visitable.js

~There is a single usage of Ceibo's `value` for only a `visitable` property.~ This is not true. the `value` is still [used](https://github.com/san650/ember-cli-page-object/blob/master/addon-test-support/properties/collection/main.js#L118) in the new Collection. But seems like it's for a reason.
The only difference between `value` and `get` is that `value` creates a [`writable` descriptor](https://github.com/san650/ceibo/blob/master/index.js#L46-L51) while `get` doesn't. I think `visitable` should be changed to leverage Ceibo's `get` since I can see a reason to use writable descriptor for it.

Use Ceibo descriptor `get` for visitable

---

addon-test-support/-private/execution_context/acceptance.js
addon-test-support/-private/execution_context/integration.js
addon-test-support/-private/execution_context/native-events-context.js
addon-test-support/-private/execution_context/rfc268.js
addon-test-support/-private/helpers.js
addon-test-support/extend/find-element-with-assert.js
addon-test-support/extend/find-element.js
addon-test-support/properties/attribute.js
addon-test-support/properties/contains.js
addon-test-support/properties/count.js
addon-test-support/properties/has-class.js
addon-test-support/properties/is-hidden.js
addon-test-support/properties/is-visible.js
addon-test-support/properties/is.js
addon-test-support/properties/not-has-class.js
addon-test-support/properties/property.js
addon-test-support/properties/text.js
addon-test-support/properties/value.js

This PR avoids direct usages of `execution-context` in the "readonly" properties. Also `ExecutionContext.run` was completely removed cause it's a no-op method now.

[refactor] Cleanup readonly properties

---

config/ember-try.js

I opened up [234](https://github.com/ember-cli/ember-try/issues/234) in `ember-try` when exploring addon-docs for this library. No one's answered me yet, so I don't know what the consensus on this behavior is, but I think in the meantime we should drop this into our scenarios to ensure that we are in fact testing what we think we are testing.
I've checked and other libraries that test against ember < 2.12 where you must use bower and they also use the `ember-try` option that explicitly removes a package. [ember-bootstrap](https://github.com/kaliber5/ember-bootstrap/blob/master/config/ember-try.js), [ember-qunit](https://github.com/emberjs/ember-qunit/blob/master/config/ember-try.js), [ember-cli-mirage](https://github.com/samselikoff/ember-cli-mirage/blob/master/config/ember-try.js) to …

explicitly remove ember-source from ember-try scenarios that rely on bower

---

AUTHORS
addon-test-support/-private/helpers.js
addon-test-support/create.js
addon-test-support/properties/collection/main.js
tests/acceptance/composition-test.js
tests/unit/-private/composition-test.js

Edit: Originally this PR was an attempt to solve both composition and extension of page objects. During the course of review, the extension aspect was removed. While it no longer solves [#181](https://github.com/san650/ember-cli-page-object/issues/181) , the tools are in place for an extension approach via some sort of custom `merge` function should someone wish to write that in app space (or should such an approach be vetted and accepted here). 
Leveraging Ceibo's ability to take custom `buildObject` functions, the definitions for each page object are stored in the Ceibo metadata so that that during composition, the page object can be substituted with its definition. This is necessary since Page object's are "special" in that they fire functions expecting a test context and make …

Enable page object composition via stored definitions

---

.travis.yml
config/ember-try.js

ember@3.9-beta started to raise a deprecation when `Ember.$` is used, which leads to failures in some tests that [expect no deprectations](https://github.com/san650/ember-cli-page-object/blob/18817c709753ecfe2e6346ee7a9641d575dfe954/tests/integration/deprecations/comma-separated-selector-test.js#L74).

Disable jquery in ember-try scenarios for modern Ember versions

---

addon-test-support/create.js
tests/integration/default-properties-test.js

Somewhere between 1.3.0 and 1.5.2, an empty create started failing.

empty create regression

---

addon-test-support/-private/action.js
addon-test-support/-private/dsl.js
addon-test-support/-private/execution_context/acceptance-native-events.js
addon-test-support/-private/execution_context/acceptance.js
addon-test-support/-private/execution_context/integration-native-events.js
addon-test-support/-private/execution_context/integration.js
addon-test-support/-private/execution_context/native-events-context.js
addon-test-support/-private/execution_context/rfc268.js
addon-test-support/macros/alias.js
package.json
tests/dummy/app/templates/application.hbs
tests/integration/deprecations/comma-separated-selector-test.js
tests/unit/-private/execution_context/acceptance-test.js
tests/unit/-private/execution_context/helpers.js
tests/unit/-private/execution_context/integration-native-test.js
tests/unit/-private/execution_context/integration-test.js
tests/unit/-private/execution_context/rfc268-test.js

An original motivation for this change was a desire to learn of how do actions+chaining work here per each context. As a result knowledge about about chainability was extracted from execution contexts was extracted to a standalone `run` function. 
For the sake of keeping a backward compatibility in legacy contexts(moduleFor) a new `andThen` hook was added. For contexts that have `andThen`, `run` waiting for the previous action to be completed before invoking a new one. I believe we should remove `andThen` in the next major release.

Extract run

---

package.json

Bump up ember-native-dom-helpers version to 0.6.x to avoid deprecation warnings because of using `merge` from @ember/polyfills

Bump up ember-native-dom-helpers

---

addon-test-support/properties/is.js
tests/unit/-private/properties/is-test.js

#442 - deprecate is 
#359 - v2 preparations

deprecate `is` property

---

addon-test-support/-private/context.js
addon-test-support/-private/execution_context.js
addon-test-support/-private/helpers.js
addon-test-support/create.js
guides/deprecations.md
tests/helpers/properties/integration-adapter.js
tests/integration/deprecations/legacy-collection-test.js
tests/integration/deprecations/set-context-test.js
tests/unit/-private/execution_context/rfc268-test.js
tests/unit/-private/supports-rfc268-test.js

Fixes #444 
`moduleForComponent` + `setContext` was a point  of much confusion for ages. With @ember/test-helpers we are able to auto-detect if it's `moduleForComponent` kind of test or not.

Deprecate setContext

---

.gitignore
.npmignore
.travis.yml
package.json
types/chaining-test.ts
types/clickable-test.ts
types/collection-test.ts
types/create-test.ts
types/extend-test.ts
types/index.d.ts
types/macros-test.ts
types/tsconfig.json
types/tslint.json

It is a result of few iterations and testing against a real APP test suite.
It covers most of the current public APIs and provides you with auto-complete or errors when you mistype something.
Some of currently public APIs are intentionally ignored. For example, the current implementation of `create` supports the following signatures:
```js
function create(definition) {}
function create(definition, options) {}
// not supported
function create(url, definition) {}
function create(url, definition, options) {}
```
I [believe](https://github.com/san650/ember-cli-page-object/issues/464), `url` in `create` should be avoided in favor of `visitable` action, so typings from this PR does only support 2 first signatures. This approach allows us to simplify typings and signal a user about a recommended …

feat: Add ambient types

---

types/tsconfig.json

After merged green https://github.com/san650/ember-cli-page-object/pull/458, CI failed with:
> Error: Errors in typescript@local for external dependencies:
../node_modules/@types/babel__core/index.d.ts(13,20): error TS2307: Cannot find module '@babel/types'.
../node_modules/@types/babel__core/index.d.ts(14,31): error TS2307: Cannot find module '@babel/parser'.
../node_modules/@types/babel__generator/index.d.ts(10,20): error TS2307: Cannot find module '@babel/types'.
../node_modules/@types/babel__template/index.d.ts(9,31): error TS2307: Cannot find module '@babel/parser'.
../node_modules/@types/babel__template/index.d.ts(10,54): error TS2307: Cannot find module '@babel/types'.
It started to fail locally as well for some reason. Have no idea why it didn't appear before.
got fix from …

Fixup ts moduleResolution

---

addon-test-support/-private/helpers.js
addon-test-support/extend/find-many.js
addon-test-support/properties/attribute.js
addon-test-support/properties/blurrable.js
addon-test-support/properties/contains.js
addon-test-support/properties/count.js
addon-test-support/properties/has-class.js
addon-test-support/properties/is-hidden.js
addon-test-support/properties/is-present.js
addon-test-support/properties/is-visible.js
addon-test-support/properties/is.js
addon-test-support/properties/not-has-class.js
addon-test-support/properties/property.js
addon-test-support/properties/text.js
addon-test-support/properties/value.js
guides/deprecations.md
tests/integration/deprecations/multiple-test.js
tests/unit/-private/properties/attribute-test.js
tests/unit/-private/properties/contains-test.ts
tests/unit/-private/properties/has-class-test.ts
tests/unit/-private/properties/is-hidden-test.ts
tests/unit/-private/properties/is-present-test.ts
tests/unit/-private/properties/is-test.js
tests/unit/-private/properties/is-visible-test.ts
tests/unit/-private/properties/not-has-class-test.ts
tests/unit/-private/properties/property-test.ts
tests/unit/-private/properties/text-test.ts
tests/unit/-private/properties/value-test.ts
tests/unit/extend/find-one-test.ts

It unnecessarily complicates internals.
`collection` or `findMany` should be used instead.
todo:

Deprecate multiple

---

addon-test-support/-private/helpers.js

With the recent finders implementation we involved `Object.entries(`, which isn't supported by IE
Since ember supports IE, we should also do it.
see:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in

Restore IE compatibility

---

addon-test-support/create.js
guides/deprecations.md
tests/integration/deprecations/string-properties-test.js

in order to unlock any strings to be considered as a scope(#408) in v2.

[deprecate] strings in definitions

---

package.json

https://github.com/keithamus/sort-package-json/pull/161 upgraded globby which drops support for node@8

Work-around failing engines for globby on CI

---

addon-test-support/extend/find-element-with-assert.js
addon-test-support/extend/find-element.js
guides/deprecations.md
guides/extend.md

The deprecation was a bit premature, since alternative finders has just appeared.
Raising a deprecation now means users will immediatelly get warnings, once update to 1.17, which is not friendly enough.
Instead of deprecation we now just recommend to migrate to `findOne`, and include a link to the codemod.
Let's deprecate it later, somewhere in scope of v2.

Remove findElement(withAssert) deprecations

---

addon-test-support/extend/find-element-with-assert.js
addon-test-support/extend/find-element.js
tests/unit/extend/find-element-test.ts
tests/unit/extend/find-element-with-assert-test.ts

since support for `findElement{WithAssert}` has been restored in v1(https://github.com/san650/ember-cli-page-object/pull/502), and the goal to deprecate the `multiple` option for attributes was achieved, we can un-deprecate multiple for finders only, and remove it together with  `findElement{WithAssert}` later.
this would also be backported to 1.17.

[v2] remove "mutliple" deprecation from finders

---

addon-test-support/extend/find-element-with-assert.js
addon-test-support/extend/find-element.js
tests/unit/extend/find-element-test.ts
tests/unit/extend/find-element-with-assert-test.ts

[backport] remove "mutliple" deprecation from finders

---

package.json

I think this was a mistake in https://github.com/san650/ember-cli-page-object/pull/490. This prevents us from getting the latest jquery without using yarn resolutions or forking.

unpin jquery

---

.travis.yml

I’ve tried to follow [this guide](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md#node-support) to set different Node versions according to the Ember CLI version but that didn’t work out so well ([here’s an example build](https://travis-ci.org/github/gnclmorais/ember-cli-page-object/builds/743370770)).
Setting the Node version to 10 [fixed the building process](https://travis-ci.org/github/gnclmorais/ember-cli-page-object/builds/743575169) (commit de132c2 allowed me to build branches that are not `master`).
This pull request’s commits can be squashed to only two: one sets the Node version to 10 and the other one (e8d872a) addresses a few issues with TravisCI configuration. Let me know what you think! 😃 
https://travis-ci.org/github/gnclmorais/ember-cli-page-object/b …

Set Node.js version to 10 in order to fix TravisCI build

---

addon-test-support/-private/helpers.js
tests/integration/deprecations/comma-separated-selector-test.js

When a text with comma is selected, the ember-cli-page-object produces a warning. Example:
```javascript
// <fieldset>
//  <button>Lorem, Ipsum</button>
// </fieldset>
import { create, clickOnText } from 'ember-cli-page-object';
const page = create({
clickOnButton: clickOnText('button')
});
page.clickOnButton('Lorem, Ipsum'); // Usage of comma separated selectors is deprecated in ember-cli-page-object
```
Fixes https://github.com/san650/ember-cli-page-object/issues/518
Conflicts with https://github.com/san650/ember-cli-page-object/pull/494

Do not warn when selecting a text with comma

---

addon-test-support/properties/collection/main.js

in the main collection.
This is done in scope of removing depdencies on Ember, see #512

v2: Drop using of EmberArray in favour of native array

---

addon-test-support/-private/context.js
addon-test-support/-private/deprecate.js
addon-test-support/-private/helpers.js
addon-test-support/create.js
addon-test-support/extend/find-many.js
addon-test-support/properties/collection.js
addon-test-support/properties/is.js
test-support/page-object.js

Fixes https://github.com/san650/ember-cli-page-object/issues/525
this allows to control proper params in a single place
Also added support for `since` and `for` options of the Ember's `deprecate(`, see [Deprecation Staging RFC](https://github.com/emberjs/rfcs/blob/master/text/0649-deprecation-staging.md)
Note: the signature of the new util is different from the upstream
Ember's `deprecte(`:
- it avoids the second condition param, so as of now, when it's
invoked, the deprecation is immediately fired. If you need it to be
run conditionally, please wrap it with a conditional statement on
the invocation side.
- there is no `options`, all the params are splatted as an utility's
arguments, which means there are not optional params anymore.

extract `deprecate(` utilility

---

addon-test-support/-private/deprecate.js
addon-test-support/-private/helpers.js
addon-test-support/create.js
test-support/page-object.js
tests/integration/deprecations/comma-separated-selector-test.js

port of few fixes from master: 
- https://github.com/san650/ember-cli-page-object/pull/535
- https://github.com/san650/ember-cli-page-object/pull/521
ignore https://github.com/san650/ember-cli-page-object/pull/530 for now. Let's come back to it after dependency upgrades( https://github.com/san650/ember-cli-page-object/pull/528) is settled. There I'd like to remove old moduleFor adapters, so after that adding of the ember-qunit@5 should be just about adding an ember-try scenario

Sync with master

---

addon-test-support/-private/deprecate.js

The internal `deprecate` wrapper imports Ember's deprecation utility from a different location than the documented one.
When running this addon against the latest version of Ember, a runtime error occurs where Ember's deprecation function is not defined.
`deprecate` documentation: https://api.emberjs.com/ember/3.24/functions/@ember%2Fdebug/deprecate

Fix `Ember.emberDeprecate` is not a function

---

addon-test-support/properties/collection.js

The docs said find and findBy but the actual names are findOne and findOneBy.

Update the names of the find methods for collection

---

config/ember-try.js

for now..
some weird build failures happen against the ember-source@4(probably because of embroider@2 + webpack; hven't checked it)

stick to ember-source@3.28 for ember-qunit@5 scenario

---

addon-test-support/adapter.js
addon-test-support/adapters/index.js
tests/helpers/index.ts
tests/unit/-private/action-test.js

This behavior has been removed in the daa0ba0efceacde6cc4eb8315a684b88472216fa
due to desire to support environments other than ember.
However, this is an ember specific addon, so it should not cause
issues to ember users.

restore RFC268 adapter as a default

---

addon/src/-private/helpers.js

We took [the advice](https://github.com/san650/ember-cli-page-object/issues/592#issuecomment-1301011970) to upgrade to v2.0.0-beta. Overall it seems pretty stable already :+1:. We're currently running into one issue, which is addressed in this PR.
---
This solves the following use case:
1. App A has a dependency on addon B.
2. App A does not have a direct dependency on @ember/jquery.
3. Addon B does have a direct dependency on @ember/jquery.
Previously, it was in this case incorrectly assumed that window.jQuery would be available when running app A.

Fix jQuery detection when @ember/jquery is only an indirect dependency

---

addon-test-support/properties/blurrable.js
addon-test-support/properties/click-on-text.js
addon-test-support/properties/clickable.js
addon-test-support/properties/fillable.js
addon-test-support/properties/focusable.js
addon-test-support/properties/triggerable.js
addon-test-support/properties/visitable.js

For issue: https://github.com/san650/ember-cli-page-object/issues/603
Added in `await` for the following docs:
http://ember-cli-page-object.js.org/docs/v1.17.x/api/blurrable
http://ember-cli-page-object.js.org/docs/v1.17.x/api/click-on-text
http://ember-cli-page-object.js.org/docs/v1.17.x/api/fillable
http://ember-cli-page-object.js.org/docs/v1.17.x/api/focusable
http://ember-cli-page-object.js.org/docs/v1.17.x/api/triggerable
http://ember-cli-page-object.js.org/docs/v1.17.x/api/visitable
All of these properties are `async` and so should be `await` ed to work.

docs: update properties which are async to be awaited in examples

---

addon/package.json
pnpm-lock.yaml
test-app/config/ember-try.js
test-app/package.json
test-app/tests/acceptance/collection-test.ts
test-app/tests/unit/-private/composition-test.ts
test-app/tests/unit/-private/properties/collection-test.ts
test-app/tests/unit/-private/properties/create-test.ts
test-app/tests/unit/-private/properties/fillable-test.ts
test-app/tests/unit/-private/properties/getter-test.ts
test-app/tests/unit/-private/properties/visitable-test.ts
test-app/tsconfig.json

- Add support for @tsconfig/ember 3.0.0
- Addresses https://github.com/san650/ember-cli-page-object/issues/613

Add support for @tsconfig/ember 3.0.0

---

addon/package.json
pnpm-lock.yaml

Supports the v3.x series of ember-test-helpers so this addon can be installed in package managers where this range is enforced with the ember-cli 5.x blueprints which require v3 of test-helpers

Widen ember-test-helpers peer range

---

addon/types.d.ts

prior to this change, it was allowed to pass the `multiple` option to the `findOne(` which is not supposed to work

types: fix `multiple` leaks

---

addon/src/properties/attribute.js
test-app/tests/unit/-private/properties/attribute-test.ts

a part of the https://github.com/san650/ember-cli-page-object/issues/617.

get rid of `$.attr(`

---

addon/types.d.ts

Hello!
I've found this small issue with return type declarations for `count` attribute while rewriting some of my tests to TS.
Link to the attribute source code for reference: https://github.com/san650/ember-cli-page-object/blob/master/addon/src/properties/count.js#L91

fix: proper type declaration for `count` attribute

---

CONTRIBUTING.md
addon/src/properties/visitable.js
test-app/tests/unit/-private/properties/visitable-test.ts

fixes https://github.com/san650/ember-cli-page-object/issues/619.
In order to remain backwards-compatible I implemented the Array and Object handler similar as $.param is doing. Could also only use 
`(new URLSearchParams(queryParams)).toString()`
but that is building array and object differently:
```
const params = {
user_id: 5,
comment_id: 1,
hello: 'world',
lorem: 'ipsum',
reply_ids: [1, 2],
search: {
author: 'ember',
topic: 'lts',
deep: {
my_array: [99, 77],
my_value: true
}
}
};
const URLSearch = new URLSearchParams(params)
const jquery = $.param(params)
decodeURIComponent(URLSearch)
decodeURIComponent(jquery)

#619 chore: get rid of `$.param`

---

addon/src/-private/better-errors.js
addon/src/macros/getter.js
test-app/tests/integration/comma-separated-selector-test.ts
test-app/tests/unit/-private/properties/getter-test.ts
test-app/tests/unit/extend/find-one-test.ts

#596 broke QUnit error messages so they now miss contextual error info like page object path and selector. This info only remained as a part of the console output.
**Before:**
This happened cause #596 relied on the `.toString()` method of the Error to build the final error message. However, that's not how the error message is supposed to be displayed in UI. 
Instead, we need the `Error.message` to be complete. Let's build it in the `Error` constructor then.
**After:**

fix: restore getter error details

---

addon/package.json

When TS is set up to not use a `moduleResolution` of `node16` or `bundler` yet (like legacy `node`/`node10`), then TS would not look into `exports`.
There is `types`, but that only works when resolving the main index module, like `import from 'ember-cli-page-object'`, but all other submodules like `ember-cli-page-object/adapter` would fail to resolve to `types.d.ts`. 
This is removing `types` in favor of `typesVersions`, supporting the same wildcard-matching that `exports` does.

Add typesVersions for resolving all type imports using legacy moduleResolution

---

addon/src/-private/helpers.js
addon/src/create.js
addon/src/properties/collection.js
test-app/tests/integration/string-properties-test.ts

Preserve getters within collections by applying their descriptors when cloning. 
Fixes #637

Support string getters within collections

---

addon/src/-private/better-errors.js
addon/src/properties/visitable.js
test-app/tests/unit/-private/properties/visitable-test.ts
test-app/tsconfig.json

This adds the actual error message from Ember's router to the (too generic) message from `visitable`. This is especially important when your test needs to know what kind of error was triggered. For example some tests might want to handle `TransitionAborted` errors differently, see https://github.com/emberjs/ember-test-helpers/issues/332#issuecomment-414641697.

Better errors from visitable

---

.github/workflows/ci.yml

it currently fails with the 
```
Running self-installer...
 WARN  GET https://registry.npmjs.org/pnpm error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/pnpm error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/pnpm: Value of "this" must be of type URLSearchParams
Error: Something went wrong, self-installer exits with code 1
```
https://github.com/san650/ember-cli-page-object/actions/runs/11084629777/job/30825358176?pr=642#step:4:13

fix(ci) upgrade pnpm/action-setup to the current latest

---

addon/package.json

Closes https://github.com/san650/ember-cli-page-object/issues/641

fix: include blueprints when publishing

---

.github/workflows/ci.yml

cause the latest scenarios require it

fix(ci) use node@16 for ember-try scenarios
