- DOCUMENTATION.md
- test-support/page-object.js
- test-support/page-object/actions.js
- test-support/page-object/attribute.js
- test-support/page-object/collection.js
- test-support/page-object/predicates.js
- test-support/page-object/queries.js
- tests/acceptance/login-test.js
- tests/unit/actions/click-on-text-test.js
- tests/unit/actions/clickable-test.js
- tests/unit/actions/fillable-test.js
- tests/unit/actions/visitable-test.js
- tests/unit/predicates/has-class-test.js
- tests/unit/predicates/is-hidden-test.js
- tests/unit/predicates/is-visible-test.js
- tests/unit/predicates/not-has-class-test.js
- tests/unit/queries/attribute-test.js
- tests/unit/queries/count-test.js
- tests/unit/queries/text-test.js
- tests/unit/queries/value-test.js
- tests/unit/test-helper.js
> Add click on text helper

- DOCUMENTATION.md
- test-support/page-object/attribute.js
- tests/acceptance/user-list-test.js
- tests/unit/queries/attribute-test.js
Implement index option on attributes and queries to make definitions more dev friendly.
> Support indexable selectors

- DOCUMENTATION.md
- test-support/page-object.js
- tests/acceptance/user-list-test.js
- tests/dummy/app/templates/users.hbs
> Add selectable helper

- DOCUMENTATION.md
- test-support/page-object.js
- test-support/page-object/custom-helper.js
- tests/acceptance/user-list-test.js
- tests/dummy/app/routes/users.js
- tests/dummy/app/templates/users.hbs
> Implement custom helpers

- DOCUMENTATION.md
- test-support/page-object/collection.js
- test-support/page-object/helpers.js
- tests/unit/components/collection-test.js
- tests/unit/custom-helper-test.js
> Improve collection item selector

- README.md
> Make full documentation easier to find on README

- test-support/page-object/collection.js
> Add error message when accessing 0th item

- test-support/page-object/collection.js
- tests/unit/components/collection-test.js
See https://github.com/san650/ember-cli-page-object/pull/73
> Assign correct scope to sub-collection items

- api/components.md
Hey, small documentation fix here.
> Correct anchor link

- bower.json
- package.json
> Bump ember cli to 1.13.15

- .travis.yml
- config/ember-try.js
Add ember versions 1.12, 1.13, 2.0, 2.1
> Add more scenarios to ember-try

- test-support/page-object/properties/is-visible.js
- tests/unit/predicates/is-visible-test.js
> `.isVisible` returns false if element doesn't exist

- test-support/page-object/helpers.js
- test-support/page-object/properties/attribute.js
- test-support/page-object/properties/contains.js
- test-support/page-object/properties/has-class.js
- test-support/page-object/properties/is-hidden.js
- test-support/page-object/properties/is-visible.js
- test-support/page-object/properties/not-has-class.js
- test-support/page-object/properties/text.js
- test-support/page-object/properties/value.js
Instead of returning a regular array. This is a problem when
not using EXTENDED_PROTOTYPES.
> Fix Ember.A(jqArray) returns jQuery array instead of Ember.Array

- CHANGELOG.md
- test-support/page-object/create.js
- tests/acceptance/actions-test.js
- tests/unit/create-test.js
Restore support of async/await (#20)
> Page object component acts like a promise

- test-support/page-object/actions/fillable.js
Closes https://github.com/san650/ember-cli-page-object/issues/141
> Add 'selectable' as JSDoc alternate name for 'fillable'

- README.md
And also who are the maintainers
> Let people know about the slack channel

- _data/navs.yml
- docs/v1.0.x/migrating.md
- docs/v1.1.x/api/actions.md
- docs/v1.1.x/migrating.md
@san650 @juanazam: Take a look and let me know what you think.
> Migration guide 0.x to 1.x

- README.md
> Update installation instructions to mention Ceibo dependency

- test-support/page-object/queries/text.js
- tests/unit/queries/text-test.js
For https://github.com/san650/ember-cli-page-object/issues/158
> Add option to avoid text normalization

- CHANGELOG.md
- addon/index.js
- addon/queries/property.js
- test-support/page-object.js
- tests/unit/queries/attribute-test.js
- tests/unit/queries/property-test.js
> Add .property property

- addon/actions/click-on-text.js
- addon/actions/clickable.js
- addon/actions/fillable.js
- addon/context.js
- addon/create.js
- addon/helpers.js
- addon/predicates/contains.js
- addon/predicates/has-class.js
- addon/predicates/not-has-class.js
- addon/queries/attribute.js
- addon/queries/property.js
- addon/queries/text.js
- addon/queries/value.js
- package.json
- tests/integration/actions-test.js
- tests/unit/actions/click-on-text-test.js
- tests/unit/actions/clickable-test.js
- tests/unit/actions/fillable-test.js
- tests/unit/create-test.js
- tests/unit/predicates/contains-test.js
- tests/unit/predicates/has-class-test.js
- tests/unit/predicates/not-has-class-test.js
- tests/unit/queries/attribute-test.js
- tests/unit/queries/property-test.js
- tests/unit/queries/text-test.js
- tests/unit/queries/value-test.js
> Better errors

- addon/actions/clickable.js
- addon/helpers.js
- tests/unit/actions/clickable-test.js
> Validate element visible on `clickable` attribute

- addon/collection.js
- tests/unit/components/collection-test.js
When an element not found error is thrown inside a collection.
Fixes #177
> Show correct PageObject path for collections

- ember-cli-build.js
> Always import ember-template-compiler in dummy app

- tests/unit/components/collection-test.js
Added test that detect broken iterations mentioned in #196
> Added tests for broken collection iteration

- addon/collection.js
- tests/unit/components/collection-test.js
- tests/unit/create-test.js
> Don't mutate definition objects

- .npmignore
This takes 13MB off the size of the installed package
> add _site to npmignore

- addon/helpers.js
- tests/unit/create-test.js
- tests/unit/test-helper.js
> Allow empty selector

- test-support/page-object/create.js
- test-support/page-object/helpers.js
- test-support/page-object/properties/custom-helper.js
This replaces all references to the global `$` with `Ember.$`
> Adds $ declaration to all files where $ is used without Ember. prefix

- _includes/head.html
- _layouts/default.html
- _layouts/page.html
- _sass/_nav-menu.scss
- _sass/_variables.scss
- _sass/intro.scss
- css/main.scss
- index.html
Adds a new index page using sass variables to make easier change color schema.
> Template redesign

- _includes/sidebar-guides.html
- guides/blueprints.md
> Add blueprints guide

- _includes/sidebar-guides.html
- guides/async-await.md
> Add async/await guide

- index.js
See https://github.com/ember-cli/ember-cli/issues/3718
> Allow addon to be used as a nested addon

- addon/-private/execution_context.js
- addon/extend.js
- tests/unit/addon-exports-test.js
Allows to plug custom behavior from outside the addon
> Register custom execution context

- _layouts/inner.html
- _sass/_buttons.scss
- _sass/_footer.scss
- _sass/_github-star.scss
- _sass/_nav-menu.scss
- _sass/_splash.scss
- _sass/_terminal.scss
- _sass/_variables.scss
- css/main.scss
- index.html
Updates the splash view to fit well on small resolutions. I'm working in a new layout of the inner template.
I created the PR to deploy it in heroku and test it.
> Site redesign

- .gitignore
- .npmignore
- package.json
- tests/helpers/properties.js
- tests/helpers/properties/integration-adapter.js
- tests/properties/attribute-test.js
- tests/properties/click-on-text-test.js
- tests/properties/clickable-test.js
- tests/properties/collection-test.js
- tests/properties/contains-test.js
- tests/properties/count-test.js
- tests/properties/create-test.js
- tests/properties/dsl-test.js
- tests/properties/fillable-test.js
- tests/properties/has-class-test.js
- tests/properties/is-hidden-test.js
- tests/properties/is-test.js
- tests/properties/is-visible-test.js
- tests/properties/not-has-class-test.js
- tests/properties/property-test.js
- tests/properties/text-test.js
- tests/properties/triggerable-test.js
- tests/properties/value-test.js
> Fix tests with newer versions of ember (and jQuery 2.x)

- addon/-private/properties/collection.js
- tests/properties/collection-test.js
Added 'forEach' method to arrayDelegateMethods so that it can be used in Collection. Also added a test for this method.
> add 'foreach' to arrayDelegateMethods

- app/blueprints/page-object-component.js
- app/blueprints/page-object-helper.js
- app/blueprints/page-object.js
> Remove invalid blueprint files

- docs/v0.11.x/api/components.md
- docs/v1.0.x/components.md
- docs/v1.1.x/components.md
- docs/v1.2.x/components.md
- docs/v1.3.x/components.md
- docs/v1.4.x/components.md
- docs/v1.5.x/components.md
- docs/v1.6.x/components.md
- docs/v1.7.x/components.md
- docs/v1.8.x/components.md
Thanks for all your work on this, I am still finding it so useful! Hopefully this triple-PR situation isn’t annoying; if it’s preferable, I could make them all one!
> Fix typo: explicitely to explicitly

- addon/-private/dsl.js
- addon/-private/properties/as.js
> Add documentation for `as` property

- addon/-private/properties/collection.js
- tests/properties/collection-test.js
> Copy testContainer configuration to collection's items

- .travis.yml
- README.md
- package.json
> Add Code Coverage

- addon/-private/dsl.js
- addon/-private/execution_context/acceptance.js
- package.json
Solves https://github.com/san650/ember-cli-page-object/issues/309.
> Use fallback for wait() from ember-test-helpers

- _data/navs.yml
- docs/v1.9.x/api/as.md
- docs/v1.9.x/api/attribute.md
- docs/v1.9.x/api/click-on-text.md
- docs/v1.9.x/api/clickable.md
- docs/v1.9.x/api/collection.md
- docs/v1.9.x/api/contains.md
- docs/v1.9.x/api/count.md
- docs/v1.9.x/api/fillable.md
- docs/v1.9.x/api/has-class.md
- docs/v1.9.x/api/is-hidden.md
- docs/v1.9.x/api/is-visible.md
- docs/v1.9.x/api/is.md
- docs/v1.9.x/api/not-has-class.md
- docs/v1.9.x/api/property.md
- docs/v1.9.x/api/text.md
- docs/v1.9.x/api/triggerable.md
- docs/v1.9.x/api/value.md
- docs/v1.9.x/api/visitable.md
- docs/v1.9.x/components.md
- docs/v1.9.x/extend.md
- docs/v1.9.x/index.md
- docs/v1.9.x/installation.md
- docs/v1.9.x/migrating.md
- docs/v1.9.x/options.md
- docs/v1.9.x/quickstart.md
- Update documentation for `v1.9.x`
> Add docs for v1.9.x

- tests/helpers/properties.js
- tests/helpers/properties/acceptance-adapter.js
- tests/helpers/properties/integration-adapter.js
- tests/unit/-private/properties/triggerable-test.js
I think we can simplify here a little bit as we've merged #327
> Cleanup test adapters

- addon/-private/properties/is-present.js
- docs.js
Also made a small improvement to `docs.js` to create the `gh-branch` if it doesn't exist yet.
> Small fix to documentation for `isPresent`

- package.json
- test-support/page-object.js
- tests/acceptance/actions-test.js
- tests/acceptance/default-properties-test.js
- tests/integration/actions-test.js
- tests/integration/context-test.js
- tests/integration/default-properties-test.js
- tests/integration/deprecations/test-support-test.js
- tests/integration/hooks-test.js
> Deprecate imports from test-support

- addon/-private/helpers.js
- package.json
- tests/integration/deprecations/comma-separated-selector-test.js
> deprecate usage of comma separated selectors

- test-support/page-object.js
- tests/integration/deprecations/test-support-test.js
follow up commit to address @magistrula 's [comment](https://github.com/san650/ember-cli-page-object/pull/368/files#r164315739)
> Make test-support deprecation message more conventional

- addon/-private/properties/collection/main.js
- tests/acceptance/collection-test.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/async-calculator.js
- tests/dummy/app/templates/async-calculator.hbs
- tests/unit/-private/properties/collection-test.js
fixes #377 
@san650 @magistrula @pzuraq
> [Collection] Preserve behavior from legacy collection for non existing item

- AUTHORS
> Add Ben Demboski to authors

- docs/v1.14.x/api/collection.md
This is a fixed collection API generated output. Suddenly the issue was in a [`@public` tag](https://github.com/san650/ember-cli-page-object/pull/389/commits/7b63a0f84266b8160ae63db91f6e6113744536e0#diff-3b664b1551d5c88bf2d403b24a164761L8)
> Fix collections API doc

- docs.js
This PR changes docs.js script to copy all the "guides/" contents to the "gh-pages" branch. 
See https://github.com/san650/ember-cli-page-object/pull/389
> Copy "guides/" to gh-pages

- addon/-private/properties/attribute.js
- addon/-private/properties/blurrable.js
- addon/-private/properties/click-on-text.js
- addon/-private/properties/clickable.js
- addon/-private/properties/collection.js
- addon/-private/properties/contains.js
- addon/-private/properties/count.js
- addon/-private/properties/fillable.js
- addon/-private/properties/focusable.js
- addon/-private/properties/getter.js
- addon/-private/properties/has-class.js
- addon/-private/properties/is-hidden.js
- addon/-private/properties/is-present.js
- addon/-private/properties/is-visible.js
- addon/-private/properties/is.js
- addon/-private/properties/not-has-class.js
- addon/-private/properties/property.js
- addon/-private/properties/text.js
- addon/-private/properties/triggerable.js
- addon/-private/properties/value.js
- addon/-private/properties/visitable.js
- docs.js
- guides/components.md
- guides/extend.md
- guides/index.md
- guides/installation.md
- guides/migrating.md
- guides/native-events.md
- guides/options.md
- guides/quickstart.md
cherry-picked latest commits from [v1.14](https://github.com/san650/ember-cli-page-object/commits/v1.14) branch
> Port 1.14 docs updates

- addon-test-support/properties/collection/main.js
- tests/unit/-private/properties/collection-test.js
see https://github.com/san650/ember-cli-page-object/pull/406#issuecomment-446722236
> Do not re-create collection on consequent access

- addon-test-support/-private/context.js
- addon-test-support/-private/helpers.js
- addon-test-support/properties/collection.js
- guides/deprecations.md
- test-support/page-object.js
some new deprecations are coming, it'd be great to have it on a single page.
> [docs] add deprecations page

- types/index.d.ts
When I deleted my custom types to use the new builtin types, I got some errors, so.. here we are :)
> add options to types

- addon-test-support/-private/execution_context.js
- tests/unit/-private/supports-rfc268-test.js
Fixes https://github.com/san650/ember-cli-page-object/issues/472
> Adjust unknown test type error message

- addon-test-support/properties/is.js
- guides/deprecations.md
Closes https://github.com/san650/ember-cli-page-object/issues/442
> [docs] Add deprecation section for "is" property

- addon-test-support/-private/helpers.js
- addon-test-support/extend/find-element-with-assert.js
- addon-test-support/extend/find-element.js
- addon-test-support/extend/find-many.js
- addon-test-support/extend/find-one.js
- addon-test-support/extend/index.js
- addon-test-support/properties/attribute.js
- addon-test-support/properties/contains.js
- addon-test-support/properties/count.js
- addon-test-support/properties/has-class.js
- addon-test-support/properties/is-hidden.js
- addon-test-support/properties/is-present.js
- addon-test-support/properties/is-visible.js
- addon-test-support/properties/not-has-class.js
- addon-test-support/properties/property.js
- addon-test-support/properties/text.js
- addon-test-support/properties/value.js
- blueprints/page-object-helper/files/tests/pages/helpers/__name__.js
- guides/deprecations.md
- guides/extend.md
- tests/unit/addon-exports-test.js
- tests/unit/extend/find-many-test.js
- tests/unit/extend/find-one-test.js
- types/index.d.ts
> adds new dom finders 

- addon-test-support/create.js
- guides/deprecations.md
- tests/integration/deprecations/create-url-argument-test.js
> [deprecate] passing URL to create

- package.json
> bump version jquery

- addon-test-support/extend/find-element-with-assert.js
- addon-test-support/extend/find-element.js
- addon-test-support/extend/find-many.js
- addon-test-support/properties/attribute.js
- addon-test-support/properties/blurrable.js
- addon-test-support/properties/contains.js
- addon-test-support/properties/has-class.js
- addon-test-support/properties/is-hidden.js
- addon-test-support/properties/is-present.js
- addon-test-support/properties/is-visible.js
- addon-test-support/properties/is.js
- addon-test-support/properties/not-has-class.js
- addon-test-support/properties/property.js
- addon-test-support/properties/text.js
- addon-test-support/properties/value.js
- tests/integration/deprecations/multiple-test.js
- tests/unit/extend/find-element-test.ts
- tests/unit/extend/find-element-with-assert-test.ts
it does appear when it should not currently
see https://github.com/san650/ember-cli-page-object/issues/496#issuecomment-608468935
> Fix "multiple" deprecation

- addon-test-support/properties/attribute.js
- tests/unit/-private/properties/attribute-test.js
> Restore jquery normalization of attributes

- addon-test-support/-private/execution_context.js
see: https://github.com/san650/ember-cli-page-object/issues/495#issuecomment-607880540
> Fallback to acceptance tests

- addon-test-support/-private/execution_context.js
port from 1.16.3 - https://github.com/san650/ember-cli-page-object/pull/499
see: https://github.com/san650/ember-cli-page-object/issues/495#issuecomment-607880540
> Forward to master "Fallback to acceptance tests" 

- addon-test-support/-private/execution_context/acceptance.js
- addon-test-support/-private/execution_context/integration.js
- addon-test-support/-private/execution_context/native-events-context.js
- addon-test-support/-private/execution_context/rfc268.js
- addon-test-support/-private/finders.js
- addon-test-support/-private/helpers.js
- addon-test-support/extend/find-element-with-assert.js
- addon-test-support/extend/find-element.js
- addon-test-support/extend/find-many.js
- addon-test-support/extend/find-one.js
- addon-test-support/properties/click-on-text/helpers.js
- tests/unit/extend/find-element-with-assert-test.ts
and extract find logic from execution contexts
> v2: group finders

- .travis.yml
- addon-test-support/-private/compatibility.js
- addon-test-support/-private/execution_context/integration-native-events.js
- addon-test-support/-private/execution_context/integration.js
- config/ember-try.js
- package.json
- tests/acceptance/actions-test.js
- tests/acceptance/collection-test.js
- tests/acceptance/composition-test.js
- tests/acceptance/default-properties-test.js
- tests/acceptance/extension-helpers-test.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/properties/acceptance-adapter.js
- tests/helpers/properties/integration-adapter.js
- tests/index.html
- tests/integration/context-test.js
- tests/integration/deprecations/legacy-collection-test.js
- tests/integration/deprecations/multiple-test.js
- tests/integration/deprecations/page-render-test.js
- tests/integration/hooks-test.js
- tests/test-helper.js
- tests/unit/-private/execution_context/acceptance-test.js
- tests/unit/-private/execution_context/integration-native-test.js
- tests/unit/-private/execution_context/integration-test.js
Fixes #524
Continues #529 by adding an ember-try scenario, and fixing a typo.
> Support ember-qunit@5

- addon-test-support/-private/helpers.js
- tests/unit/extend/find-element-with-assert-test.ts
- tests/unit/extend/find-one-test.ts
a part of https://github.com/san650/ember-cli-page-object/issues/512
> get rid of ember assert

- config/ember-try.js
> satisfy qunit peerDep of the ember-qunit@5.1.2

- addon-test-support/-private/helpers.js
> get rid of ember `isPresent(`

- addon-test-support/-private/action.js
- addon-test-support/-private/helpers.js
- addon-test-support/create.js
- addon-test-support/properties/attribute.js
- addon-test-support/properties/blurrable.js
- addon-test-support/properties/click-on-text.js
- addon-test-support/properties/clickable.js
- addon-test-support/properties/collection.js
- addon-test-support/properties/contains.js
- addon-test-support/properties/count.js
- addon-test-support/properties/fillable.js
- addon-test-support/properties/focusable.js
- addon-test-support/properties/has-class.js
- addon-test-support/properties/is-hidden.js
- addon-test-support/properties/is-present.js
- addon-test-support/properties/is-visible.js
- addon-test-support/properties/not-has-class.js
- addon-test-support/properties/property.js
- addon-test-support/properties/text.js
- addon-test-support/properties/triggerable.js
- addon-test-support/properties/value.js
- addon-test-support/properties/visitable.js
a part of https://github.com/san650/ember-cli-page-object/issues/512
> use object spread over the Ember `assign(`

- tests/dummy/app/templates/application.hbs
- tests/dummy/app/templates/async-calculator.hbs
- tests/dummy/app/templates/calculator.hbs
- tests/dummy/app/templates/components/calculating-device.hbs
- tests/dummy/app/templates/components/clickable-component.hbs
- tests/dummy/app/templates/components/html-render.hbs
- tests/dummy/app/templates/components/login-form.hbs
- tests/dummy/app/templates/components/user-list.hbs
- tests/dummy/app/templates/html-render.hbs
- tests/dummy/app/templates/inputs.hbs
- tests/helpers/properties/integration-adapter.js
- tests/helpers/properties/rendering-adapter.js
- tests/helpers/start-app.js
- tests/unit/adapters/acceptance-test.js
cherry-pick https://github.com/san650/ember-cli-page-object/pull/541 into v2-beta
> v2: reduce deprecations

- addon-test-support/-private/deprecate.js
- package.json
- tests/integration/deprecations/comma-separated-selector-test.js
- tests/integration/deprecations/create-url-argument-test.js
- tests/integration/deprecations/string-properties-test.js
- tests/integration/deprecations/test-support-test.js
- tests/unit/-private/deprecate-test.js
a part of the https://github.com/san650/ember-cli-page-object/issues/512
> Reimplement deprecate

- package.json
> avoid beta of the ember-cli-babel

- package-lock.json
- package.json
since the moduleFor adapters has been removed already(https://github.com/san650/ember-cli-page-object/pull/564)
> remove native-dom-helpers

- .gitignore
needed for https://github.com/san650/ember-cli-page-object/pull/576
> gitignore v2 addon directories

- tests/unit/-private/properties/property-test.ts
- tsconfig.json
- types/global.d.ts
- types/index.d.ts
fixes https://github.com/san650/ember-cli-page-object/issues/589
> types(v1)/no synthetic imports

- addon-test-support/-private/helpers.js
- addon-test-support/create.js
- addon-test-support/properties/attribute.js
- addon-test-support/properties/blurrable.js
- addon-test-support/properties/click-on-text.js
- addon-test-support/properties/click-on-text/helpers.js
- addon-test-support/properties/clickable.js
- addon-test-support/properties/collection/legacy.js
- addon-test-support/properties/collection/main.js
- addon-test-support/properties/contains.js
- addon-test-support/properties/count.js
- addon-test-support/properties/fillable.js
- addon-test-support/properties/focusable.js
- addon-test-support/properties/has-class.js
- addon-test-support/properties/is-hidden.js
- addon-test-support/properties/is-present.js
- addon-test-support/properties/is-visible.js
- addon-test-support/properties/is.js
- addon-test-support/properties/not-has-class.js
- addon-test-support/properties/property.js
- addon-test-support/properties/text.js
- addon-test-support/properties/triggerable.js
- addon-test-support/properties/value.js
- addon-test-support/properties/visitable.js
- tests/helpers/start-app.js
Reference: https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign
> Fix assign deprecation

- addon/src/properties/visitable.js
- test-app/tests/unit/-private/properties/visitable-test.ts
before the change a raw ember error was used, which was not informative enough
> v2: improve `visitable` error message

- addon/src/-private/action.js
- addon/src/macros/getter.js
- test-app/tests/unit/-private/action-test.js
- test-app/tests/unit/-private/properties/getter-test.ts
> fail fast if no callback passed
